// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.first_run", false);
user_pref("app.normandy.user_id", "49cc27dd-4328-450a-884c-2d7e3c4c2fec");
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1542367893);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1542368013);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1542383850);
user_pref("app.update.lastUpdateTime.recipe-client-addon-run", 1542367773);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1542367653);
user_pref("app.update.lastUpdateTime.telemetry_modules_ping", 1542019311);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 1542368133);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.capacity", 675840);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.download.panel.shown", true);
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1539698207);
user_pref("browser.laterrun.bookkeeping.sessionCount", 13);
user_pref("browser.migration.version", 69);
user_pref("browser.newtabpage.activity-stream.impressionId", "{d548118e-7422-4e9a-be84-f8b740b8c0be}");
user_pref("browser.newtabpage.activity-stream.improvesearch.topSiteSearchShortcuts.havePinned", "google,amazon");
user_pref("browser.newtabpage.activity-stream.migrationExpired", true);
user_pref("browser.newtabpage.activity-stream.migrationLastShownDate", 1539640800);
user_pref("browser.newtabpage.activity-stream.migrationRemainingDays", 3);
user_pref("browser.newtabpage.pinned", "[{\"url\":\"http://start.fedoraproject.org/\",\"title\":\"Fedora Project - Start Page\"},{\"url\":\"https://google.com\",\"label\":\"@google\",\"searchTopSite\":true},{\"url\":\"https://amazon.com\",\"label\":\"@amazon\",\"searchTopSite\":true}]");
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.onboarding.notification.last-time-of-changing-tour-sec", 1542018995);
user_pref("browser.onboarding.notification.prompt-count", 6);
user_pref("browser.onboarding.notification.tour-ids-queue", "onboarding-tour-addons,onboarding-tour-customize,onboarding-tour-default-browser,onboarding-tour-performance,onboarding-tour-private-browsing,onboarding-tour-screenshots,onboarding-tour-addons,onboarding-tour-customize,onboarding-tour-default-browser");
user_pref("browser.onboarding.seen-tourset-version", 2);
user_pref("browser.onboarding.tour-type", "new");
user_pref("browser.pageActions.persistedActions", "{\"version\":1,\"ids\":[\"bookmark\",\"bookmarkSeparator\",\"copyURL\",\"emailLink\",\"addSearchEngine\",\"sendToDevice\",\"pocket\",\"screenshots\"],\"idsInUrlbar\":[\"pocket\",\"bookmark\"]}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.places.smartBookmarksVersion", 8);
user_pref("browser.safebrowsing.provider.google4.lastupdatetime", "1542385620162");
user_pref("browser.safebrowsing.provider.google4.nextupdatetime", "1542387412162");
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1542383839999");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1542387439999");
user_pref("browser.search.countryCode", "DE");
user_pref("browser.search.region", "DE");
user_pref("browser.sessionstore.upgradeBackup.latestBuildID", "20181009141245");
user_pref("browser.slowStartup.averageTime", 3359);
user_pref("browser.slowStartup.samples", 3);
user_pref("browser.startup.homepage_override.buildID", "20181009141245");
user_pref("browser.startup.homepage_override.mstone", "62.0.3");
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"PersonalToolbar\":[\"personal-bookmarks\"],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"home-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"downloads-button\",\"library-button\",\"sidebar-button\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"]},\"seen\":[\"developer-button\"],\"dirtyAreaCache\":[\"PersonalToolbar\",\"nav-bar\",\"toolbar-menubar\",\"TabsToolbar\"],\"currentVersion\":14,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("browser.urlbar.timesBeforeHidingSuggestionsHint", 0);
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1539698215049");
user_pref("devtools.onboarding.telemetry.logged", true);
user_pref("distribution.fedora.bookmarksProcessed", true);
user_pref("distribution.iniFile.exists.appversion", "62.0.3");
user_pref("distribution.iniFile.exists.value", true);
user_pref("dom.push.userAgentID", "7e95f7e093b5491eb1193b660e5b4e38");
user_pref("extensions.blocklist.lastModified", "Thu, 15 Nov 2018 09:04:34 GMT");
user_pref("extensions.blocklist.pingCountTotal", 6);
user_pref("extensions.blocklist.pingCountVersion", 6);
user_pref("extensions.databaseSchema", 27);
user_pref("extensions.getAddons.cache.lastUpdate", 1542367899);
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.lastAppBuildId", "20181009141245");
user_pref("extensions.lastAppVersion", "62.0.3");
user_pref("extensions.lastPlatformVersion", "62.0.3");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webextensions.uuids", "{\"webcompat@mozilla.org\":\"8c364084-b547-4be0-8817-38922e4d7d2e\",\"screenshots@mozilla.org\":\"ade092c4-e430-4012-9e6f-df933abbf1ad\"}");
user_pref("idle.lastDailyNotification", 1542367711);
user_pref("lightweightThemes.usedThemes", "[]");
user_pref("media.gmp-gmpopenh264.abi", "x86_64-gcc3");
user_pref("media.gmp-gmpopenh264.lastUpdate", 1540808469);
user_pref("media.gmp-gmpopenh264.version", "1.7.1");
user_pref("media.gmp-manager.buildID", "20181009141245");
user_pref("media.gmp-manager.lastCheck", 1542367675);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("network.cookie.prefsMigrated", true);
user_pref("network.predictor.cleaned-up", true);
user_pref("pdfjs.enabledCache.initialized", true);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pdfjs.previousHandler.preferredAction", 4);
user_pref("places.database.lastMaintenance", 1542024879);
user_pref("places.history.expiration.transient_current_max_pages", 112348);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("privacy.sanitize.pending", "[{\"id\":\"newtab-container\",\"itemsToClear\":[],\"options\":{}}]");
user_pref("security.sandbox.content.tempDirSuffix", "e9c80783-6d55-4e59-b594-7b6cf778a861");
user_pref("services.blocklist.addons.checked", 1542368012);
user_pref("services.blocklist.gfx.checked", 1540669325);
user_pref("services.blocklist.onecrl.checked", 1540669325);
user_pref("services.blocklist.pinning.checked", 1540669325);
user_pref("services.blocklist.plugins.checked", 1540669325);
user_pref("services.settings.clock_skew_seconds", 1);
user_pref("services.settings.last_etag", "\"1542272674851\"");
user_pref("services.settings.last_update_seconds", 1542368012);
user_pref("signon.importedFromSqlite", true);
user_pref("storage.vacuum.last.index", 1);
user_pref("storage.vacuum.last.places.sqlite", 1542024879);
user_pref("toolkit.startup.last_success", 1542383818);
user_pref("toolkit.telemetry.cachedClientID", "7c4ca670-6edc-4c7a-b1fd-4dcc0c5a9619");
user_pref("toolkit.telemetry.previousBuildID", "20181009141245");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
